### ISSUE TITLE
Large texts are split/chunked?

### ISSUE THREAD

**Issue by tmikaeld** [iuioiua/r2d2#143]
I have values of about 100kb each, but they're split and or not saved/read properly.

Any idea what the issue can be? Does the TCP buffer size need to be increased?

I check the Deno docs about the Deno.connect but it doesn't mention anything about this.

**Comment by iuioiua** [comment]
Could you please provide me with a minimal reproducible snippet of this issue?

**Comment by tmikaeld** [comment]
Sorry, it was rushed conclusion. It was the typical `JSON.stringification` -> `obj.toString()` mistake.

Closing this issue.

**Comment by tmikaeld** [comment]
@iuioiua 

I found the edge-case, here's a reproduction:
https://github.com/tmikaeld/redis-bug

`deno run --allow-net --allow-read redis-bug.js`

If the body and json is a certain size, then the last " is always omitted making the json parse fail.

**Comment by iuioiua** [comment]
Hi @tmikaeld, sorry for the delay. I've released [v1.1.11](https://github.com/iuioiua/r2d2/releases/tag/v1.1.11), which should fix the issue. The TL;DR is that the HTML text contained a "©" symbol, which is 2 bytes long. The previous request constructor assumed all characters are 1 byte long. The fix was to use the byte length of strings instead of their character length. An obvious flaw in hindsight, but so are all flaws, I suppose.

**Comment by tmikaeld** [comment]
No need to apologize, thanks for fixing it so fast! It's an easy thing to miss and i choose this library just because it is light on the feet and fast, I expected there to be some hick-ups along the way. I'm just glad i found it, it wasn't easy :-D
